---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

permissions:
  contents: read
  pull-requests: write

jobs:
  workflows:
    uses: mdegat01/addon-workflows/.github/workflows/pr-labels.yaml@main
